class TimerComponent extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.innerHTML = `
            <style>
                .time-display {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                }
                input {
                    width: 50px;
                    font-size: 2em;
                    text-align: center;
                    border: none;
                    background: transparent;
                    color: var(--text-color, #333);
                    border-bottom: 2px solid var(--input-border, #ccc);
                    margin: 0 5px;
                    transition: color 0.3s;
                }
                span {
                    font-size: 2em;
                }
            </style>
            <div class="time-display">
                <input type="number" id="hours" value="0" min="0">
                <span>:</span>
                <input type="number" id="minutes" value="0" min="0" max="59">
                <span>:</span>
                <input type="number" id="seconds" value="0" min="0" max="59">
            </div>
        `;

        this.hoursInput = this.shadowRoot.querySelector('#hours');
        this.minutesInput = this.shadowRoot.querySelector('#minutes');
        this.secondsInput = this.shadowRoot.querySelector('#seconds');
    }

    getTimeInSeconds() {
        const hours = parseInt(this.hoursInput.value) || 0;
        const minutes = parseInt(this.minutesInput.value) || 0;
        const seconds = parseInt(this.secondsInput.value) || 0;
        return hours * 3600 + minutes * 60 + seconds;
    }

    setTime(totalSeconds) {
        const hours = Math.floor(totalSeconds / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const seconds = totalSeconds % 60;
        this.hoursInput.value = hours;
        this.minutesInput.value = minutes;
        this.secondsInput.value = seconds;
    }
}

customElements.define('timer-component', TimerComponent);

const timer = document.querySelector('timer-component');
const startBtn = document.getElementById('start');
const stopBtn = document.getElementById('stop');
const resetBtn = document.getElementById('reset');
const presets = document.querySelector('.presets');
const toggleSoundBtn = document.getElementById('toggle-sound');
const toggleThemeBtn = document.getElementById('toggle-theme');
const alarmSelect = document.getElementById('alarm-select');
const alarmSound = document.getElementById('alarm-sound');
const animationContainer = document.getElementById('animation-container');
const mouseAnimation = document.getElementById('mouse-animation');

let intervalId = null;
let remainingTime = 0;
let soundEnabled = true;
let userInteracted = false;
let lastSetTime = 0;

// Hardcoded list of alarm sounds (filenames in snd/ folder)
// In a real application, this list might be generated by a server-side script
const alarmSounds = [
    { name: 'Loud Alarm', file: 'https://raw.githubusercontent.com/qmin9339-glitch/Timer/main/loud_alarm_sound.mp3' },
    // Add more alarm sounds here if available in the snd/ folder
    // { name: 'Alarm 02', file: 'snd/Alarm02.wav' },
];

function populateAlarmSelect() {
    alarmSelect.innerHTML = ''; // Clear existing options
    alarmSounds.forEach(alarm => {
        const option = document.createElement('option');
        option.value = alarm.file;
        option.textContent = alarm.name;
        alarmSelect.appendChild(option);
    });

    // Set initial selection from localStorage or default
    const savedAlarm = localStorage.getItem('selectedAlarm');
    if (savedAlarm) {
        alarmSelect.value = savedAlarm;
        alarmSound.src = savedAlarm;
    } else {
        alarmSelect.value = alarmSounds[0].file;
        alarmSound.src = alarmSounds[0].file;
    }
}

function unlockAudio() {
    if (userInteracted) return;
    alarmSound.play();
    alarmSound.pause();
    alarmSound.currentTime = 0;
    userInteracted = true;
}

function updateButtonVisibility(isTimerRunning) {
    document.body.classList.toggle('timer-running', isTimerRunning);
    stopBtn.classList.toggle('hidden', !isTimerRunning);
}

function startTimer() {
    if (intervalId) return;
    lastSetTime = timer.getTimeInSeconds(); // Store the initial time
    remainingTime = lastSetTime;
    if (remainingTime <= 0) return;

    updateButtonVisibility(true);
    animationContainer.style.display = 'block';
    intervalId = setInterval(() => {
        remainingTime--;
        timer.setTime(remainingTime);
        if (remainingTime <= 0) {
            clearInterval(intervalId);
            intervalId = null;
            animationContainer.style.display = 'none';
            if (soundEnabled) {
                alarmSound.loop = true; // Loop the alarm
                alarmSound.play();
            }
        }
    }, 1000);
}

function stopTimer() {
    clearInterval(intervalId);
    intervalId = null;
    animationContainer.style.display = 'none';
    updateButtonVisibility(false);
    alarmSound.pause();
    alarmSound.currentTime = 0;
    alarmSound.loop = false; // Stop looping
    timer.setTime(lastSetTime); // Set timer back to last set time
}

function resetTimer() {
    stopTimer(); // This will also reset the display to lastSetTime
    timer.setTime(0); // Then reset to 0
    lastSetTime = 0;
}

// --- Event Listeners ---
document.body.addEventListener('click', unlockAudio, { once: true });

startBtn.addEventListener('click', startTimer);
stopBtn.addEventListener('click', stopTimer);
resetBtn.addEventListener('click', resetTimer);

presets.addEventListener('click', (e) => {
    if (e.target.tagName === 'BUTTON') {
        const time = parseInt(e.target.dataset.time);
        timer.setTime(time);
        lastSetTime = time; // Update lastSetTime when a preset is selected
    }
});

toggleSoundBtn.addEventListener('click', () => {
    soundEnabled = !soundEnabled;
    toggleSoundBtn.textContent = `Sound: ${soundEnabled ? 'On' : 'Off'}`;
});

toggleThemeBtn.addEventListener('click', () => {
    document.body.classList.toggle('dark-mode');
    const isDarkMode = document.body.classList.contains('dark-mode');
    toggleThemeBtn.textContent = `Theme: ${isDarkMode ? 'Dark' : 'Light'}`;
});

alarmSelect.addEventListener('change', (e) => {
    alarmSound.src = e.target.value;
    localStorage.setItem('selectedAlarm', e.target.value);
});

// Initialize alarm select on load
populateAlarmSelect();